import Head from 'next/head';
import NavBar from '../components/NavBar';
import AboutScreen from '../components/AboutScreen';

const About = () => {
  return (
    <>
      <Head>
        <title>Acerca de - Diego Fedez</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <NavBar />
      <AboutScreen />
    </>
  );
};

export default About;
