import Head from 'next/head';
import { useState } from 'react';
import NavBar from '../components/NavBar';
import ContactScreen from '../components/ContactScreen';
import ContactForm from '../components/ContactForm';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faComments } from '@fortawesome/free-solid-svg-icons';

const Contact = () => {
  const [contactActive, setContactActive] = useState(false);

  return (
    <>
      <Head>
        <title>Contacto - Diego Fedez</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <NavBar />
      <ContactForm
        contactActive={contactActive}
        setContactActive={setContactActive}
      />
      <ContactScreen
        contactActive={contactActive}
        setContactActive={setContactActive}
      />
      <aside className='flex justify-center items-center gap-3 mb-6'>
        <h1 className='text-lg md:text-xl font-bold'>Ponte en contacto</h1>
        <FontAwesomeIcon
          icon={faComments}
          className='text-custom text-3xl hover:cursor-pointer hover:text-custom2 transition-all duration-200'
          onClick={() => setContactActive(!contactActive)}
        />
      </aside>
    </>
  );
};

export default Contact;
